apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: NAMESPACE
  objref:
    kind: Kafka
    name: kafka
    apiVersion: platform.confluent.io/v1beta1
  fieldref:
    fieldpath: metadata.namespace

configurations:
  - config.yaml

resources:
  - ../../base

components:
  - ../../components/mtls
  - ../../components/lb-exposed
  - ../../components/rbac

