apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
- name: credential
  options:
    disableNameSuffixHash: true
  files:
    - digest.txt
    - digest-users.json
    - basic.txt
    - plain.txt
    - plain-users.json
    - ldap.txt

patchesStrategicMerge:
  - patches.yaml

resources:
  - certificates.yaml
