apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data-zk-snapshot-0
spec:
  volumeSnapshotClassName: csi-aws-vsc
  source:
    persistentVolumeClaimName: data-zookeeper-0
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data-zk-snapshot-1
spec:
  volumeSnapshotClassName: csi-aws-vsc
  source:
    persistentVolumeClaimName: data-zookeeper-1
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data-zk-snapshot-2
spec:
  volumeSnapshotClassName: csi-aws-vsc
  source:
    persistentVolumeClaimName: data-zookeeper-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-zookeeper-clone-0
spec:
  dataSource:
    name: data-zk-snapshot-0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-zookeeper-clone-1
spec:
  dataSource:
    name: data-zk-snapshot-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-zookeeper-clone-2
spec:
  dataSource:
    name: data-zk-snapshot-2
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: txnlog-zk-snapshot-0
spec:
  volumeSnapshotClassName: csi-aws-vsc
  source:
    persistentVolumeClaimName: txnlog-zookeeper-0
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: txnlog-zk-snapshot-1
spec:
  volumeSnapshotClassName: csi-aws-vsc
  source:
    persistentVolumeClaimName: txnlog-zookeeper-1
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: txnlog-zk-snapshot-2
spec:
  volumeSnapshotClassName: csi-aws-vsc
  source:
    persistentVolumeClaimName: txnlog-zookeeper-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: txnlog-zookeeper-clone-0
spec:
  dataSource:
    name: txnlog-zk-snapshot-0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: txnlog-zookeeper-clone-1
spec:
  dataSource:
    name: txnlog-zk-snapshot-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: txnlog-zookeeper-clone-2
spec:
  dataSource:
    name: txnlog-zk-snapshot-2
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data0-kafka-snapshot-0
spec:
  volumeSnapshotClassName: csi-aws-vsc
  source:
    persistentVolumeClaimName: data0-kafka-0
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data0-kafka-snapshot-1
spec:
  volumeSnapshotClassName: csi-aws-vsc
  source:
    persistentVolumeClaimName: data0-kafka-1
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data0-kafka-snapshot-2
spec:
  volumeSnapshotClassName: csi-aws-vsc
  source:
    persistentVolumeClaimName: data0-kafka-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data0-kafka-clone-0
spec:
  dataSource:
    name: data0-kafka-snapshot-0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data0-kafka-clone-1
spec:
  dataSource:
    name: data0-kafka-snapshot-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data0-kafka-clone-2
spec:
  dataSource:
    name: data0-kafka-snapshot-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper-clone
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  storageClass:
    name: ebs-sc
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka-clone
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  dataVolumeCapacity: 10Gi
  storageClass:
    name: ebs-sc
