apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: partition
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - rbac-kafka-cluster
    labelSelectors:
      app: kafka
  direction: to
  target:
    mode: all
    selector:
      namespaces:
        - openldap
